package com.jeenms.test.greendao3.entity;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.jeenms.test.greendao3.entity.Teacher;
import com.jeenms.test.greendao3.entity.User;

import com.jeenms.test.greendao3.entity.TeacherDao;
import com.jeenms.test.greendao3.entity.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig teacherDaoConfig;
    private final DaoConfig userDaoConfig;

    private final TeacherDao teacherDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        teacherDaoConfig = daoConfigMap.get(TeacherDao.class).clone();
        teacherDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        teacherDao = new TeacherDao(teacherDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Teacher.class, teacherDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        teacherDaoConfig.getIdentityScope().clear();
        userDaoConfig.getIdentityScope().clear();
    }

    public TeacherDao getTeacherDao() {
        return teacherDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
